package com.qingning.sweetlime.core.mapping

/**
 * 上标映射（对齐 qiwangming 上标生成器）。
 * 注意 q / Q 在源站被映射成两个码点的 "ᴼ̴"，S 为 "ᔆ"，属该站特例。
 */
internal val SUPERSCRIPT_MAP: Map<Char, String> = hashMapOf(
    '0' to "⁰",
    '1' to "¹",
    '2' to "²",
    '3' to "³",
    '4' to "⁴",
    '5' to "⁵",
    '6' to "⁶",
    '7' to "⁷",
    '8' to "⁸",
    '9' to "⁹",
    'A' to "ᴬ",
    'B' to "ᴮ",
    'C' to "ᶜ",
    'D' to "ᴰ",
    'E' to "ᴱ",
    'F' to "ᶠ",
    'G' to "ᴳ",
    'H' to "ᴴ",
    'I' to "ᴵ",
    'J' to "ᴶ",
    'K' to "ᴷ",
    'L' to "ᴸ",
    'M' to "ᴹ",
    'N' to "ᴺ",
    'O' to "ᴼ",
    'P' to "ᴾ",
    'Q' to "ᴼ̴",
    'R' to "ᴿ",
    'S' to "ᔆ",
    'T' to "ᵀ",
    'U' to "ᵁ",
    'V' to "ⱽ",
    'W' to "ᵂ",
    'X' to "ˣ",
    'Y' to "ʸ",
    'Z' to "ᶻ",
    'a' to "ᵃ",
    'b' to "ᵇ",
    'c' to "ᶜ",
    'd' to "ᵈ",
    'e' to "ᵉ",
    'f' to "ᶠ",
    'g' to "ᵍ",
    'h' to "ʰ",
    'i' to "ⁱ",
    'j' to "ʲ",
    'k' to "ᵏ",
    'l' to "ˡ",
    'm' to "ᵐ",
    'n' to "ⁿ",
    'o' to "ᵒ",
    'p' to "ᵖ",
    'q' to "ᴼ̴",
    'r' to "ʳ",
    's' to "ˢ",
    't' to "ᵗ",
    'u' to "ᵘ",
    'v' to "ᵛ",
    'w' to "ʷ",
    'x' to "ˣ",
    'y' to "ʸ",
    'z' to "ᶻ",
)

/**
 * 下标映射（对齐 qiwangming 下标生成器）。
 * 源站对大小写输出完全相同（D→d、G→g、Q→q、W→w 等缺字用普通字母补位），
 * 缺字处用音乐符号 𝄴 / 𝆑 / 𝆎 补位，均属该站特例。
 */
internal val SUBSCRIPT_MAP: Map<Char, String> = hashMapOf(
    '0' to "₀",
    '1' to "₁",
    '2' to "₂",
    '3' to "₃",
    '4' to "₄",
    '5' to "₅",
    '6' to "₆",
    '7' to "₇",
    '8' to "₈",
    '9' to "₉",
    'A' to "ₐ",
    'B' to "ᵦ",
    'C' to "𝄴",
    'D' to "d",
    'E' to "ₑ",
    'F' to "𝆑",
    'G' to "g",
    'H' to "ₕ",
    'I' to "ᵢ",
    'J' to "ⱼ",
    'K' to "ₖ",
    'L' to "ₗ",
    'M' to "ₘ",
    'N' to "ₙ",
    'O' to "ₒ",
    'P' to "ₚ",
    'Q' to "q",
    'R' to "ᵣ",
    'S' to "ₛ",
    'T' to "ₜ",
    'U' to "ᵤ",
    'V' to "ᵥ",
    'W' to "w",
    'X' to "ₓ",
    'Y' to "ᵧ",
    'Z' to "𝆎",
    'a' to "ₐ",
    'b' to "ᵦ",
    'c' to "𝄴",
    'e' to "ₑ",
    'f' to "𝆑",
    'h' to "ₕ",
    'i' to "ᵢ",
    'j' to "ⱼ",
    'k' to "ₖ",
    'l' to "ₗ",
    'm' to "ₘ",
    'n' to "ₙ",
    'o' to "ₒ",
    'p' to "ₚ",
    'r' to "ᵣ",
    's' to "ₛ",
    't' to "ₜ",
    'u' to "ᵤ",
    'v' to "ᵥ",
    'x' to "ₓ",
    'y' to "ᵧ",
    'z' to "𝆎",
)
